# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sorcering <- function(A = NULL, t_sim = 2L, tsteps = "monthly", C0 = NULL, N0 = NULL, Cin = NULL, Nin = NULL, xi = NULL, calcN = FALSE, calcNbalance = FALSE) {
    .Call(`_sorcering_sorcering`, A, t_sim, tsteps, C0, N0, Cin, Nin, xi, calcN, calcNbalance)
}

